sudo: false
language: python

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env:
    - PYTHON_VERSION="3.6"
  - python: 2.7
    env:
    - PYTHON_VERSION="2.7"

notifications:
  slack: colour-science:Y6lPPcN7y53Js94geqUpqsAP

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:O:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda2-3.19.0-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.19.0-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - PACKAGES="python=${PYTHON_VERSION}"
  - PACKAGES="${PACKAGES} matplotlib"; if [ ${MATPLOTLIB_VERSION} ]; then PACKAGES="${PACKAGES}=${MATPLOTLIB_VERSION}"; fi
  - PACKAGES="${PACKAGES} numpy"; if [ ${NUMPY_VERSION} ]; then PACKAGES="${PACKAGES}=${NUMPY_VERSION}"; fi
  - PACKAGES="${PACKAGES} pyqt"; if [ ${PYQT_VERSION} ]; then PACKAGES="${PACKAGES}=${PYQT_VERSION}"; fi
  - PACKAGES="${PACKAGES} scipy"; if [ ${SCIPY_VERSION} ]; then PACKAGES="${PACKAGES}=${SCIPY_VERSION}"; fi

install:
  - conda create --yes --quiet -n colour-test ${PACKAGES} pip setuptools nose
  - source activate colour-test
  - pip install six coverage coveralls flake8 mock==1.0.1

before_script:
  - export PYTHONWARNINGS=ignore

script:
  - flake8 colour
  - nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS --with-coverage --cover-package=colour colour

after_success:
  - coveralls
