sudo: false
language: python

matrix:
  fast_finish: true
  include:
  - python: 3.7
    env:
    - PYTHON_VERSION="3.7"
  - python: 2.7
    env:
    - PYTHON_VERSION="2.7"

notifications:
  slack: colour-science:Y6lPPcN7y53Js94geqUpqsAP

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:O:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda

install:
  - conda create --yes --quiet -n colour-ci python=${PYTHON_VERSION} coverage coveralls flake8 imageio matplotlib mock nose pandas pip pyqt scipy six
  - source activate colour-ci
  - python -c "import imageio;imageio.plugins.freeimage.download()"

before_script:
  - export PYTHONWARNINGS=ignore

script:
  - flake8 colour
  - nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS --with-coverage --cover-package=colour colour

after_success:
  - coveralls
